# python review

short reveiw about some core concepts in pythin exemplified by objects in the numpy library

### goals:
- recall basic python vocab
- practice markdown syntax

## libraries and packages
**library:** os a collection of code that we can use to perform specific tasks in our programs. it can be a single file or multiple files.

**numpy:**

- core library for numerical computing in python
- many of libraries use numpy arrays as their building blocks
- computations on numpy objects are optimized for speed and memory usage

lets import numpy with is **standard abbreviation** `np`:

In [2]:
import numpy as np

## variables

**variable:** a name we assign to a particular object in python

example:

In [3]:
# assign a small array to variable a
a = np.array([ [1,1,2], [3,5,8] ])

to view a variables value from out jupyter notebook

In [4]:
# run cell with variable name to show value

a

array([[1, 1, 2],
       [3, 5, 8]])

In [5]:
# use `print` function to print value

print(a)

[[1 1 2]
 [3 5 8]]


## convention: use `snake_case` for naming variables.

this is the convention we will use in the course. Why? `my-variable` or `MyVariable` or `myVariable`,
PEP 8 - Style Guide for Python Code recommends snake_case.

**Remember thtat variable names should both be descriptive and concise**

## Objects

**object:** (informally speaking) is a bundle of *properties* and *actions* about something specific.

Example:

Object: data frame
Properties: number of rows, names of columns, and date created
Actions: selecting a specific row or adding a new column

A variable is the name we give a specific object, and the same object can be referenced by different variables.

In practice, we can often use the word variable and object interchangeably.

## Types

Every object in Python has a **type**, the type tells us what kind o fobject we have.
We can also call the type of an object, the **class** of and object. So class and object both mean what kind of object we have.

In [6]:
print(a)

[[1 1 2]
 [3 5 8]]


In [7]:
# see the type/class of a variable/object by using `type` function
type(a)

numpy.ndarray

the `numpy.ndarray` is the core object/data type of the NumPy package.

In [8]:
print(a[0,0])

1


In [9]:
type(a[0,0])

numpy.int64

`numpy.int64` is not the standard Python integer type `int`.

`numpy.int64` is a special data type in Numpy telling us that 1 is an integer stored as a 64 bit number

check in: access the value 5 in array `a`

In [15]:
print(a[1,1])

5


## functions

`print` was our first example of a python **function**

functions take in a set of **arguments** separated by commas, and use those arguments to create an **output**.

In the course we'll be using argument and parameter interchangeably. but they do have slightly different meanings

we can ask for info about what as function does by executing ? followed by the function name:

In [16]:
?print

Docstring:
print(value, ..., sep=' ', end='\n', file=sys.stdout, flush=False)

Prints the values to a stream, or to sys.stdout by default.
Optional keyword arguments:
file:  a file-like object (stream); defaults to the current sys.stdout.
sep:   string inserted between values, default a space.
end:   string appended after the last value, default a newline.
flush: whether to forcibly flush the stream.
Type:      builtin_function_or_method


what we obtain is a **docstring**, a special type of comment that is used to document how a fuction (or a class, or module) works.

notice is that there are different types of arguents inside the functions parenthesis

roughtly speaking, a function has two types of arguments:

- **non optional arguments**: arguments *you* have to specify for the unction to work
- **optional arguments**: arguments that are pre-filled with a default value by the function, but you can override them. optional arguments appear inside the parenthesis () in the form `optional_argument = default_value`.

Example

`end` us a parameter in `print` with default value a new line
we can pass the value `:-)` to this parameter so that it finished the line with `:-)` instead:

In [18]:
print("change the end parameter", end =  ":-)")

change the end parameter:-)

## attributes and methods

an object in python has attributes and methods.

- **attributes**: a property of the object, some piec of info abot it.
- **method**: a procedure associated with an object, so it is an action where the main ingredient is the object itself

## check in 

make class fish, give it 3 methods and 3 attributes

attributes: swimming style, diet, derpness
methods: vibe, dance, cromch

In [20]:
a

array([[1, 1, 2],
       [3, 5, 8]])

In [21]:
# t is an example of an attribute, it returns the transpose of an array
print(a.T)

[[1 3]
 [1 5]
 [2 8]]


In [22]:
type(a.T)

numpy.ndarray

In [23]:
# shape another attribute tells us the shape of the array
print(a.shape)
print(type(a.shape))

(2, 3)
<class 'tuple'>


In [25]:
print("dim:", a.ndim, "| type", type(a.ndim))

dim: 2 | type <class 'int'>


attributes can have many different data types

some examples of methods:

In [26]:
#  the min method returns the minimum value in the array along a specified axis
print(a)

a.min(axis = 0)

[[1 1 2]
 [3 5 8]]


array([1, 1, 2])

In [27]:
# run min method with axis
a.min()

1

remember, methods are functions associated with an object. we can confirm this

In [29]:
# method tolist() to transform array into lsit
a.tolist()

[[1, 1, 2], [3, 5, 8]]

### exercise

In [30]:
?print

Docstring:
print(value, ..., sep=' ', end='\n', file=sys.stdout, flush=False)

Prints the values to a stream, or to sys.stdout by default.
Optional keyword arguments:
file:  a file-like object (stream); defaults to the current sys.stdout.
sep:   string inserted between values, default a space.
end:   string appended after the last value, default a newline.
flush: whether to forcibly flush the stream.
Type:      builtin_function_or_method


In [31]:
int1 = 77
int2 = "99"

In [35]:
print(int1, int2, int1, sep = "%")

77%99%77
